### PR TITLE
Introduce fzf (cli fuzzy search)

### PR DESCRIPTION
**Pull request by Kyslik**
Introduce [fzf](https://github.com/junegunn/fzf)

In case someone does not know what fuzzy search is:

while in sublime text hit `⌘+p` and start typing...

### CODE REVIEW

**Comment by sb2nov** [comment]
Hi, Can you add a line for tracking this file in the Summary.md ?

https://github.com/sb2nov/mac-setup/blob/master/SUMMARY.md

**Comment by Kyslik** [comment]
Will do :)

**Comment by Kyslik** [comment]
Done.

**Comment by sb2nov** [comment]
Thanks for adding this :) I'll merge this now and will have to deploy next week as I have been traveling for some work stuff. 

Would you be interested in being added as a contributor on the repo so that you can make changes more easily ?

**Comment by Kyslik** [comment]
No problem, I use fzf a lot its really fast :)

Sure I will try my best, since this guide is really good idea!

>**Note**: I will need to read contribution guide again :D.

**Pull request merged**
