### PR TITLE
Shortcuts for skipping a word or jump to start || end of line

### PR DESCRIPTION
**Pull request by Kyslik**
@sb2nov I am not sure if gitbook handles tables.

### CODE REVIEW

**Comment by sb2nov** [comment]
I'll check if gitbook will render this correctly. Thanks a lot for adding this. 👍

**Comment by sb2nov** [comment]
Seems to have worked perfectly. http://sourabhbajaj.com/mac-setup/iTerm/

**Comment by Kyslik** [comment]
Nice 👍 , I will add more information later from other answers not just the accepted one. I'll merge it right away so you don't need to check it.

**Comment by sb2nov** [comment]
Feel free to edit and update as you see fit. Thanks again.

**Pull request merged**
