### PR TITLE
MacTex and BasicTex information included

### PR DESCRIPTION
**Pull request by bsheikh**
Includes information about BasicTex and MacTex. Also explains the difference between BasicTex and MacTex.

### CODE REVIEW

**Comment by sb2nov** [comment]
Thanks for adding this, really appreciate the help :+1:

**Comment by bsheikh** [comment]
No problem, anytime.

**Comment by bsheikh** [comment]
The updated information about LaTeX does not show up.

**Comment by sb2nov** [comment]
Sorry I think I forgot to deploy. Should be fixed now.

**Pull request merged**
