### PR TITLE
Update Cask.md

### PR DESCRIPTION
**Pull request by hisabimbola**

### CODE REVIEW

**Comment by Kyslik** [comment]
Was wondering if suggesting casks is needed at all.

What do you think @simeg ?

**Comment by simeg** [comment]
@Kyslik I like casks a lot, I use them as much as possible! Why do you think they are not needed?

I vote 👍 on this PR.

**Comment by Kyslik** [comment]
I use casks myself a lot too! I am just suggesting not to "suggest" anything since whatever list we come up with is going to be opinionated.

**Comment by simeg** [comment]
In this case I think it's ok to be opinionated. We are just suggesting some cask packages we think could be useful, we're not saying "_you should use this tool A, not tool B, because we think tool A is better_". If anyone want to add more cask packages to the list I think that would be ok too :)

With editors for example, we have (or at least plan to have) information about many of them. So we're not opinionated in that sense, we just give people curated and condensed information about what choices they have so they can make an educated decision on what tools to use. If they don't like it they can just create a PR to change it.

I see cask packages the same way, we're just saying "_Hey, there's this nice way of installing applications - check it out!_". What I really hope people do is go and find their own applications to download.

At least this is how I see things :) Let me know what you think.

**Comment by sb2nov** [comment]
+1000 to what @simeg mentioned. 

Also, I feel having a bit of opinion helps the reader, an example would be how to use project-based environments in different languages (Python, Ruby). Sure you can globally install everything but probably less I ideal. 

I vote for merging the PR as well.

**Comment by Kyslik** [comment]
This PR fixes the shell command I guess, and there are plenty suggestions already :)

**Pull request merged**
