### PR TITLE
Add sudoers permission instruction to system preferences

### LINKED ISSUE #236: Running sudo without specifying password each time
### I'm Submitting a ...

```
[ ] Bug report
[X] Tool/language/etc documentation request
```

### Tool/Language/etc

Typing password for sudo commands would be pain at times. Because there would be multiple softwares to install and each and everytime we should enter the password.
### Other Information
Modify the sudoers file and implicitly trust the mac user as sudo user.

### PR DESCRIPTION
**Pull request by worldofprasanna**
fixes #236

### CODE REVIEW

**Comment by simeg** [comment]
How I see it is that the sudo command is there for a reason, by disabling it you're potentially opening up for security issues with your user. What if someone gets access to your system? Then they'd have super user permission.

I like this approach more:
>@Kyslik: [..] Perhaps better way is to increase sudo timeout or maybe use `-1` for the timeout; so current shell does need sudo password only once.

I don't like recommending major security risks in a guide aimed at the average Joe.

@worldofprasanna Maybe we can phrase this differently? Instead of giving permanent super user access we could explain how to increase the timeout (what @Kyslik said), but also mention the risks with it. What do you think?

**Comment by worldofprasanna** [comment]
@simeg @Kyslik 	- Yes. I haven t thought about this point before. Might be I will rephrase it and mention the potential issue it can lead to. Also will mention the alternate approach.

Thanks for your thoughts 👍

**Comment by simeg** [comment]
@worldofprasanna I'm sorry if I wasn't clear enough - I don't think we should include giving permanent sudo access _at all_. Instead I think we _only_ should include the approach where we give sudo access temporarily. I consider permanent sudo access really bad practice and I don't think we should encourage it.

The system admins around the world who might actually need this are well aware of it, the average developer does not need to know about it. My 2 cents..

What I recommend is:
- Include info about how to give current shell sudo access without being prompted for a password (or increase the timeout)
- Include the potential risks this could have

**Comment by hugovk** [comment]
I agree with @simeg.

Even increasing the timeout reduces the security. And if you need sudo a lot, maybe there's a better way of doing things.

**Comment by worldofprasanna** [comment]
@simeg 	I got your point about security concern in using this solution in some server. I had rephrased the approach to edit the sudoers file.

@hugovk I am always using this approach to avoid giving password everytime. What are the other ways to do this ? Please let me know.

**Comment by simeg** [comment]
@worldofprasanna Thinking about this some more and reading your changes I'm not sure if I think this information belongs in this guide. From what I know this isn't a common issue, having to type your password in when doing sudo, so keeping it in this guide which is targeted for developers setting up their new machine (or new tool etc.) doesn't feel right. It's more of a system administrator thing, I feel like.

We always appreciate contributions but they have to fit the purpose of the guide. I'm sorry but I have to vote for this to not be merged.

**Comment by worldofprasanna** [comment]
@simeg Yes. No probs. Thanks again for lot of info. Please feel free to close the pull request.

**Pull request closed without merging**
