### PR TITLE
pip installation guide added

### PR DESCRIPTION
**Pull request by raavanan**
How to setup pip in OSX.

### CODE REVIEW

**Comment by raavanan** [comment]
#95 solve this issue

**Comment by sb2nov** [comment]
https://github.com/sb2nov/mac-setup/tree/master/Python can you update the text here itself. We could say something like

Check if pip is installed otherwise follow the instructions in the section below and not create a new file.

**Comment by raavanan** [comment]
@sb2nov sure will update the PR.

**Comment by raavanan** [comment]
@sb2nov PR updated.

**Comment by sb2nov** [comment]
Thanks

**Pull request merged**
