### PR TITLE
Added Docker quick help

### PR DESCRIPTION
**Pull request by cesarcosta99**
I added this little help to guide people who can get the same problem I've passed through.

BTW, great job with this repo. 😃

### CODE REVIEW

**Comment by sb2nov** [comment]
Actually do you want to move this page to using docker-for-mac native instead of going via a VM. As now that is the official method.

You need to make changes like `brew cask install docker` instead of the toolbox.

**Comment by cesarcosta99** [comment]
Alright, I'll do the changes as soon as possible.

**Comment by sb2nov** [comment]
Awesome, thanks for the help.

**Comment by simeg** [comment]
I vote for closing this due to inactivity.

Yes/no?

@sb2nov @Kyslik

**Comment by sb2nov** [comment]
+1 to closing as outdated. @cesarcosta99 feel free to reopen whenever you want to work on this again.

**Pull request closed without merging**
