### PR TITLE
Add Travis CI integration; Fixes #162

### LINKED ISSUE #162: Use CI tool for build status
I think it would be cool to use Travis (or any other CI tool, but I really like Travis) to know the build status for each PR and each merge to master. I imagine it running `gitbook build` on every PR and if that command fails we know that we should fix it before merging it. I use this for all my projects and it improves my confidence when merging PRs.

If you think it's a good idea you're the only person who can setup the Travis connection @sb2nov, as you're the owner of this repo.

### PR DESCRIPTION
**Pull request by sb2nov**
Testing the build.

### CODE REVIEW

**Comment by sb2nov** [comment]
@simeg PTAL

**Comment by Kyslik** [comment]
@sb2nov what is PTAL? 3-4rd google search result "Acronym of please take another look;" :D thanks.

**Comment by simeg** [comment]
I also have no idea what PTAL means 😄 

But this looks good, awesome!

**Comment by sb2nov** [comment]
Ha, might just be a habit I picked at my workplace. We sort of use it as "Please take a look" similar to please review.

**Comment by Kyslik** [comment]
For more acronyms see https://github.com/golang/go/wiki/CodeReview

**Comment by simeg** [comment]
I really like the `s/foo/bar/g`, will be using it in the future 😄

**Pull request merged**
