### PR TITLE
Add issue and contribution templates

### PR DESCRIPTION
**Pull request by simeg**
I like consistency. I think this repo needs more consistency, I also think it needs more contributions. With the contribution template I hope more people will contribute and that they will think that it's easier to do so.

With the issue template I hope to make things easier for us, the maintainers, to find and resolve the issue.

What do you think?

### CODE REVIEW

**Comment by sb2nov** [comment]
This is a really great idea. Thank you so much for adding this. 

How about we also add a page in the guide that has names of all the people who have contributed to it? As I think it is important to acknowledge that this was work done by a lot of different folks.

**Comment by simeg** [comment]
@sb2nov Sure, that could be done. I like the idea, but I'm not sure about the execution.

I see two approaches:
1) Everything is done manually, someone enters all 54 contributors and makes a nice looking page of it. Whenever someone new contributes someone of the maintainers (or the new contributor) adds that person to the list.

2) We set it up to be a complete automatic process, I found [this tool](https://github.com/mgechev/github-contributors-list) which sounds like it could simplify the process. In my mind this approach takes a lot of time to setup. It needs to be run automatically for each new person that contributes. Hmm..

My opinion about 1) is that I will not participate in doing that. If someone else wants to do that, sure, but I'm not up for maintaining such a thing. We have a [contribution page](https://github.com/sb2nov/mac-setup/graphs/contributors) here on Github that I think is sufficient.

So then 2) is the way to go, in my opinion, but idk if I think it's that important to do this right now. 

So all in all, if you want to do it I think it's a good idea but I don't want to do it for reasons stated above.

**Comment by sb2nov** [comment]
@simeg 100% agreed with your assessment, I think doing it manually would be a lot of effort and not worth the effort.

I'll try and see if I can automate this as part of the build script if possible over the weekend, otherwise, we can just leave stuff as is. Thanks for the link to the node script, I'll try to play around with it. 

Regardless I think the contributor and issue guide adding in the PR will simplify things a lot.

**Comment by sb2nov** [comment]
Added https://github.com/sb2nov/mac-setup/blob/master/contributors.py that takes care of updating the list whenever the publish script is run.

**Pull request merged**
