### PR TITLE
Remove unneeded quote

### PR DESCRIPTION
**Pull request by sofyanhadia**

### CODE REVIEW

**Comment by sb2nov** [comment]
Can you resolve the merge conflict in the PR ?

**Comment by sofyanhadia** [comment]
Conflict resolved, please review @sb2nov 
Thx :)

**Comment by sb2nov** [comment]
@sofyanhadia I don't see any changes in the PR. Can you check ?

**Comment by sb2nov** [comment]
Closing for now as it seems the change was already in the prev PR

**Pull request closed without merging**
