### PR TITLE
Don't use terminal prompt for single line commands

### PR DESCRIPTION
**Pull request by simeg**
Having the terminal prompt makes it harder to copy-paste the command.
Only use them for examples where the output is shown, so it's obvious
that is the command and what is the result.

WDYT? @sb2nov @hugovk @Kyslik

### CODE REVIEW

**Comment by sb2nov** [comment]
+1 have run into this myself multiple times.

**Comment by hugovk** [comment]
Good idea!

How about replacing the ones like with indents with ones with `bash` or `sh` formatting, like the others?

So for example instead of:

````
```
    cd /usr/local/Homebrew/
```
````

Do:

````
```bash
cd /usr/local/Homebrew/
```
````

So then instead of plain block:


    cd /usr/local/Homebrew/

We'll get some formatting:

```bash
cd /usr/local/Homebrew/
```

**Comment by simeg** [comment]
@hugovk Hmm I thought that was already the case. If not I will update that too!

**Comment by simeg** [comment]
I've started doing the work proposed by @hugovk but it's lots of manual work so not yet done. Thanks for merging!

**Pull request merged**
