### PR TITLE
Correct misspelling of MySQL

### PR DESCRIPTION
**Pull request by kaveet**
MySQL was mistakenly spelled "MyySql"

### CODE REVIEW

**Comment by hugovk** [comment]
Hmm, turns out it was an intentional misspelling. Commit https://github.com/sb2nov/mac-setup/commit/774b0a751a312e76c0bc5ed5421b8a07315158ae says:

```
<!-- This is intentially named MyySql as this was causing a 404 when hosted with github pages -->
<!-- TODO: Fix this once we figure out the issue more -->
```

See also https://github.com/sb2nov/mac-setup/commit/f63714b3cbcc178d035b4af1b5f7453d3fced2d7#commitcomment-23908642.

@kaveet Please can you turn on GH Pages for your fork and see if this still causes a 404? If not, please could you also update `SUMMARY.md`? Thanks!

**Comment by kaveet** [comment]
Mine seems to serve the page correctly: https://kaveet.github.io/mac-setup/MySQL/

Thanks for catching `SUMMARY.md`!

**Comment by hugovk** [comment]
Looks good.

@sb2nov Please could you check this? Was there some other case where it 404d? Thanks!

**Comment by sb2nov** [comment]
Yeah it might have been fixed in github pages now but originally if you had the string mysql in the url it threw a 404. Since it is working in the gh pages for the fork we should accept this.

**Pull request merged**
