### PR TITLE
Adding Fasd command line utility

### PR DESCRIPTION
**Pull request by 0xbharath**
This commit adds documentation to add Fasd command-line utility.

### CODE REVIEW

**Comment by simeg** [comment]
Hi!

This PR made me think what this guide should contain. I can't speak for what @sb2nov's thought was when creating it, but how I see it it should focus on the essential tools / libraries / languages needed to "get going" with programming on a mac machine.

I'm also guilty of adding these non-essential sections (tree, ack - now I'm thinking we should remove them) and I'm not trying to throw any shade on you, @0xbharath!

I don't want this guide to be another "awesome-mac" list, but instead help users setup their machines quickly so they can be productive.

Thoughts? @sb2nov @hugovk @Kyslik + anyone else

**Comment by hugovk** [comment]
Hi! I would tend to agree. As the README starts:

> This guide covers the basics of setting up a development environment on a new Mac. Whether you are an experienced programmer or not, this guide is intended for everyone to use as a reference for setting up your environment or installing languages/libraries.

**Comment by 0xbharath** [comment]
That makes sense. The value I got out of the documentation is that I could set up my MacOS quickly without having to search around.

However, I do see some value in probably having a separate section on essential command-line utilities but I understand that this can be subjective and the list can get exhaustive.

**Comment by simeg** [comment]
> [...] I understand that this can be subjective and the list can get exhaustive.

Yes, exactly. 

We do appreciate contributions but this one I will close. Thanks @0xbharath! 🙂 I will delete the sections I added for ack and tree.

**Pull request closed without merging**
