### PR TITLE
Use yarn over npm for speed

### PR DESCRIPTION
**Pull request by simeg**

### CODE REVIEW

**Comment by hugovk** [comment]
Is it worth it on Travis CI too?

It takes ~35s to `npm install`.

https://travis-ci.org/sb2nov/mac-setup/builds/381817378#L448

**Comment by simeg** [comment]
Good idea, added it!

**Comment by sb2nov** [comment]
Thanks.

**Comment by hugovk** [comment]
See https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn for caching.

**Comment by Kyslik** [comment]
@simeg isn't it slower because of security audit?

**Comment by simeg** [comment]
@Kyslik Do you mean that npm is slower because of security audit? You mean `npm audit`? Not sure if that's being run during the CI process.

I enabled caching, it should speed the build time up.

**Comment by Kyslik** [comment]
@simeg yea, for example https://travis-ci.org/sb2nov/mac-setup/builds/381817378#L458, but now its irrelevant since we are on yarn.

**Comment by simeg** [comment]
@Kyslik Ah, didn't know `npm install` automatically did an audit every time it installed.

**Pull request merged**
